# INSTALAR IMAGENES
FROM node:12

# CREAR CARPETA
RUN mkdir -p /usr/src/app

# NAVEGAR HASTA EL DIRECTORIO
WORKDIR /usr/src/app

# COPIAR LOS PAQUETES.JSON
COPY package*.json ./

# EJECUTAR LOS PAQUETES.JSON
RUN npm install

# COPIAR EL CODIGO FUENTE (SRC, ETC) AL DIRECTORIO CREADO. AGREGAR .DOCKERINGNORE PARA NO COPIAR NODE_MODULES
COPY . .

# PUERTO
EXPOSE 3000

# CMD [ "npm", "start" ]
CMD [ "npm", "run", "dev" ]